---
encoding: UTF-8
markdown: redcarpet
highlighter: null
exclude: ['app.json', 'config.ru', 'Gemfile', 'Gemfile.lock', 'Procfile', 'LICENSE', 'README.md', 'CHANGELOG.md', 'plastic-example-site.jpg']
name: Jekyll Plastic
url: http://www.spacesofplay.com
asset_url: "/assets"
sass:
  sass_dir: _scss
  style: :compressed
assets:
  cache: true
  js_compressor: uglifier
tag_page_layout: tag
tag_page_dir: tags
tag_permalink_style: pretty
ftp_host: 'example.com'
ftp_dir: '/example'
ftp_passive: false
ftp_username: 'username'
---